"""Rule explanations and generated catalog, sourced from rule metadata."""

from goodhart.rules import all_rules
from goodhart.rules.base import Rule


def explain(rule: Rule) -> str:
    """Explain behavior, evidence limits and the legitimate interpretation."""
    return (
        f"{rule.id} {rule.name}\n"
        f"Default severity: {rule.default_severity}\n"
        f"Applies to: {', '.join(sorted(rule.applies_to))}\n"
        f"Patch mode: {'supported' if rule.supports_patch_mode else 'unsupported'}\n\n"
        f"How checked: {rule.details}\n\n"
        f"Why flagged: {rule.why_flagged}\n\n"
        f"Legitimate when: {rule.legit_if}\n"
    )


def catalog() -> str:
    """Generate docs/rules.md deterministically from the live registry."""
    lines = [
        "# Rules",
        "",
        "<!-- Generated by scripts/generate_rules.py; edit rule metadata. -->",
        "",
        "Findings require review and do not establish intent. Allowed findings remain",
        "visible and do not count toward the configured exit threshold.",
        "",
        "| ID | Name | Default severity | Applies to |",
        "|---|---|---|---|",
    ]
    for rule in all_rules():
        lines.append(
            f"| {rule.id} | {rule.name} | {rule.default_severity} | "
            f"{', '.join(sorted(rule.applies_to))} |"
        )
    for rule in all_rules():
        lines.extend(
            [
                "",
                f"## {rule.id} {rule.name}",
                "",
                f"**Default severity:** {rule.default_severity}",
                "",
                f"**Applies to:** {', '.join(sorted(rule.applies_to))}",
                "",
                f"**Patch mode:** {'supported' if rule.supports_patch_mode else 'unsupported'}",
                "",
                f"**How checked:** {rule.details}",
                "",
                f"**Why flagged:** {rule.why_flagged}",
                "",
                f"**Legitimate when:** {rule.legit_if}",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"
